### ISSUE TITLE
I can't figure out how is implemented Opus codec?

### ISSUE THREAD

**Issue by Daparrag** [dh1tw/remoteAudio#11]
Dear Tobias:

Could you describe me how did you integrated opus in remote audio implementation?

**Comment by dh1tw** [comment]
Hi @Daparrag,

I'm using for Opus the [Go binding](https://github.com/hraban/opus) written by @hraban. It's just a think layer on top of the Opus C lib and the function signatures, arguments and constants have been held close to the ones from the C library. This means that you should definitely have a look into the documentation of the OPUS codec and it's API. It's crucial to understand how it works and how to use the API.

The implementation is amazingly straight forward. You will find the implementation details in [audio/player_async.go](https://github.com/dh1tw/remoteAudio/blob/master/audio/player_async.go) and [audio/recorder_async.go](https://github.com/dh1tw/remoteAudio/blob/master/audio/recorder_async.go).

You basically initialise the Opus codec and get in return either an [encoder](https://opus-codec.org/docs/opus_api-1.2/group__opus__encoder.html#gaa89264fd93c9da70362a0c9b96b9ca88) or a decoder. from then on, you just need to feed it with audio frames. Just make sure that the audio frames have the supported length (2.5, 5, 10, 20, 40 or 60 ms).

I hope this helps!
