### ISSUE TITLE
Error when starting remoteAudio

### ISSUE THREAD

**Issue by khkremer** [dh1tw/remoteAudio#20]
I followed the build instructions in the Wiki. I am using a Raspberry Pi 3 running Buster. When I try to start remoteAudio, I am getting this error message:

panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.1()
	/home/pi/go/src/github.com/lucas-clemente/quic-go/internal/handshake/unsafe.go:20 +0xc8

I don't know anything about go, but I am generally pretty good at following instructions. 

Thanks, 

Karl Heinz - K5KHK

**Comment by dh1tw** [comment]
Hey Karl Heinz, 

I think one of remoteAudio's dependencies requires go version 1.12. You can download the latest 1.12 release from [golang.org](https://golang.org/dl/). ARMV6 is probably the best choice for the Raspberry Pi3. 

Please let me know if this fixes the problem.

73 Tobias
DH1TW

**Comment by khkremer** [comment]
Tobias,

Thanks for the tip. I’ll give that a try. 

Karl Heinz - K5KHK 

Karl Heinz Kremer
PDF Acrobatics Without a Net 
PDF Software Development, Training and More... 
http://www.khkonsulting.com

**Comment by dh1tw** [comment]
Hi Karl Heinz,
sorry for the delay, but I wanted to let you know that I have updated the repo and fixed the dependencies with the newly introduced go modules. You should now be able to compile remoteAudio with go 1.13. You can also download prebuild binaries on the [release page](https://github.com/dh1tw/remoteAudio/releases).
