### ISSUE TITLE
build instructions a protoc

### ISSUE THREAD

**Issue by K6TD** [dh1tw/remoteAudio#32]
The build wiki might still need this step:
source $HOME/protobuf/bin/protobufrc
KR

**Comment by dh1tw** [comment]
Actually, Ubuntu 20.04 comes now with the `protobuf-compiler` version 3.6. This good enough. I recommend installing  `protobuf-compiler` through aptitude.
`# apt install protobuf-compiler`

I already updated the Dockerfiles used for [cross compiling remoteAudio](https://github.com/dh1tw/remoteAudio-xcompile) but I forgot to add it to the manual build instructions in the wiki. Thanks!
